config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'users/new'
  root 'static_pages#home'
  # Static views
  get '/home',      to: 'static_pages#home'
  # User Views
  get '/signup',    to: 'users#new'
  post '/signup',   to: 'users#create'
  # Sessions Views
  get '/login',     to: 'sessions#new'
  post '/login',    to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  # Post views
  get '/create',           to: 'posts#new'
  post '/create',          to: 'posts#create'
  # Model Resources
  resources :users
  resources :posts, only: [:show, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :topic
  validates :user_id, presence: true
  validates :title, presence: true, length: {maximum: 50}
  validates :content, presence: true, length: {maximum: 1024}
  validates :views, presence: true, numericality: {greater_than_or_equal_to: 0} 
end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :posts
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  attr_accessor :remember_token
  before_save { self.email = email.downcase }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  validates :email, presence: true, length: { maximum: 254, },
      format: { with: VALID_EMAIL_REGEX },
      uniqueness: { case_sensitive: false }

  validates :phone, presence: true, length: { in: 10..13}, numericality: { only_integer: true }

  has_secure_password
  validates :password, presence: true, length: {minimum: 6}, allow_nil: true

  def User.digest(string)
    cost=ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : 
                                                BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, remember_token)
  end

  def set_lastlogin
    update_attribute(:lastlogin, Time.now)
  end
  
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest,nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  private
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger]="Please log in."
        redirect_to login_url
      end
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :logged_in_user, only: [:new, :create, :destroy]

  def new
    @post = Post.new
    @topics = Topic.all
  end

  def show
    @post = Post.find(params[:id])
    @post.increment!(:views)
    @user = @post.user
    @topic = @post.topic
  end

  def create
    @topics = Topic.all
    post_params[:topic] = Topic.find(Integer(post_params[:topic_id]))
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = 'Post successfully created!'
      redirect_to @post
    else
      render 'new'
    end
  end

  def destroy
  end

  private

    def post_params
      params.require(:post).permit(:title, :topic_id, :content)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user  = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])# Log the user in and redirect to the user's show page.
      log_in user
      params[:session][:remember_me] =='1'? remember(user) : forget(user)
      redirect_back_or user
    else # Create an error message.
      flash.now[:danger]='Invalid email/password combination'
      render'new'
    end
  end

  def destroy 
    log_out if logged_in?
    redirect_to root_url
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    @display = "recent"
    @posts = Post.where(:created_at => (1.month.ago)..(Date.today+1.day))
    @users = User.all.order(lastlogin: :desc).limit(12)
    @topics = Topic.all
    @topposts = Post.order(views: :desc).limit(5)
  end


end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :logged_in_user, only:[:index,:edit,:update,:destroy]
  before_action :correct_user, only:[:edit,:update]
  before_action :admin_user, only: :destroy

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = 'Welcome to the Sample App!'
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user =User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else 
      render 'edit' 
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to home_path
  end

  private

    def user_params
      params.require(:user).permit(:displayname, :email, :phone, :password, :password_confirmation)
    end

    def correct_user 
      @user=User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # [1, pg. 178]
  def page_title(current_page = '')
    title = "News Plus"
    if current_page.empty?
      title
    else
      current_page + " | " + title
    end
  end

  def navlink_class(path)
    if current_page?(path)
      "active"
    elsif current_page?(root_path) && path == home_path
      "active"
    else
      ""
    end
  end

end
 

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    user.update_attribute(:lastlogin, Time.now)
    session[:user_id]=user.id
  end

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def current_user?(user)
    user == current_user  
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id]) 
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end
  
  def logged_in?
    !current_user.nil?
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user=nil
  end

  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end
  
  # Stores the URL trying to be accessed.
  def store_location
    session[:forwarding_url]=request.original_url if request.get?
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end
module StaticPagesHelper

  def home_button_class(display, button_value)
    if display == button_value
      "active-button"
    else
      ""
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user, size = 80)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.displayname, class:"gravatar")
  end

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div>
    Developed for RAD2020 by Matthew Walters (s3780012) | Friday Group 3
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-inverse navbar-static-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href=<%= home_path %>>News Plus</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="<%= navlink_class(home_path) %>"><%= link_to 'Home', home_path %></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">News<b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><a href="#">Popular News 1</a></li>
          <li><a href="#">Popular News 2</a></li>
        </ul>
      </li>
      <% if logged_in? %>
        <% if @current_user.displayname %>
          <li class="<%= navlink_class(current_user) %>"><%=link_to @current_user.displayname, current_user%></li>
        <% else %>
          <li class="<%= navlink_class(current_user) %>"><%=link_to @current_user.email, current_user%></li>
        <% end %>
      <% end %>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li class="dropdown">
        <% if logged_in? %>
          <a href="#" class="user-image dropdown-toggle" data-toggle="dropdown">
            <%= gravatar_for(@current_user, 60) %>
          </a>
          <ul class="dropdown-menu">
              <li><%=link_to"Profile", current_user%></li>
                  <li><%=link_to"Settings", edit_user_path(current_user)%></li>
                  <li class="divider"></li>
                  <li><%=link_to"Log out", logout_path, method: :delete %></li>
          </ul>
        <% else %>
          <a href="#" class="user-image dropdown-toggle" data-toggle="dropdown">
            <%= image_tag("account_circle_white.svg", alt: "Logged Out User") %>
          </a>
          <ul class="dropdown-menu">
              <li><%=link_to"Log in", login_path%></li>
          </ul>
        <% end %>
      </li>
    </ul>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%# [1, pg 178]%>
    <title><%=page_title(yield(:title))%></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">
  </head>
  
  <body>
    <%= render 'layouts/header' %>
    <div class="container-fluid">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%=message_type%>"><%=message%></div>
      <%end%>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %> 
  </body>
</html>

app/views/posts/_post_thin.html.erb
<tr>
  <td class="post">
    <div class="post-image">
      <%= gravatar_for(post.user, 48) %>
    </div>
    <div class="container-fluid">
      <div class="row">
        <div class="post-heading col-xs-12">
          <%= link_to post.title, post %>
        </div>
        <div class="post-details col-xs-9">
          Post by <%= link_to post.user.displayname, post.user %>, Date: <%= post.created_at %>, Topic: <%= post.topic.name %>
        </div>
        <div class="post-stats col-xs-3">
          [X] commments | <%= post.views %> views
        </div>
      </div>
    </div>
  </td>
</tr>

app/views/posts/new.html.erb
<%provide(:title,"New Post")%>
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <h3>New Post</h3>
    <%=form_for(:post) do |f|%>
      <%= render'shared/error_messages_posts' %>
      <%=f.label :title%>
      <%=f.text_field :title, class: 'form-control'%>
      <%=f.label :topic%>
      <%=f.collection_select :topic_id, @topics, :id, :name%>
      <%=f.label :content%>
      <%=f.text_area :content, placeholder: "Write your new post...", class: 'form-control'%>
      <%=f.submit 'Post', class: "btn btn-primary"%>
    <%end%>
  </div>
</div>

app/views/posts/show.html.erb
<%provide(:title,@post.title)%>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h4>Author</h4>
      <h5>
        <%=gravatar_for @user%>
        <%=@user.displayname%>
      </h5>
      </br>
      </br>
      </br>
      </br>
      </br>
      <h1><%=@post.title%><h1>
      <h5><%=@post.created_at.to_date%> | <%=@topic.name%> | <%=@post.views%> <h5>
      <p><%=@post.content%><p>
    </section>
  </aside>
</div>

app/views/shared/_error_messages.html.erb
<%if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%=pluralize(@user.errors.count,"error")%>.
    </div>
    <ul>
    <%@user.errors.full_messages.each do|msg|%>
      <li><%=msg%></li>
    <%end%>
    </ul>
  </div>
<%end%>

app/views/shared/_error_messages_posts.html.erb
<%if @post.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%=pluralize(@post.errors.count,"error")%>.
    </div>
    <ul>
    <%@post.errors.full_messages.each do|msg|%>
      <li><%=msg%></li>
    <%end%>
    </ul>
  </div>
<%end%>

app/views/static_pages/home.html.erb
<%provide(:title,"Home")%>
<div class="container-fluid">
  <div class="row">
    <div class="col-md-8">
      <div class="options-section-top section home-form">
        <div class="btn-group" role="group">
          <button type="button" class="btn btn-default <%= home_button_class(@display, "recent") %> " onclick='window.location.href = "/home";'>Recent Posts</button>
          <button type="submit" value="submit" form="selected-topics" class="btn btn-default <%= home_button_class(@display, "selected") %>">Selected Topics Only</button>
          <% if logged_in? %>
            <button type="button" class="btn btn-default" onclick='window.location.href = "<%= edit_user_path(current_user) %>";'>My Settings</button>
          <% end %>
        </div>
        <div class="input-group">
          <form action="">
            <input type="text" class="form-control" placeholder="Search">
            <span class="input-group-btn">
              <button class="btn btn-default" type="submit"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></button>
            </span>
          </form>
        </div>
        <div class="new-post-btn">
          <button type="button" class="btn btn-primary btn-md" onclick='window.location.href = "/create";'>New Post</button>
        </div>
      </div>
      <table class="table table-bordered">
        <th>News Posts</th>
        <tbody>
          <% @posts.each do |post|%>
            <%= render 'posts/post_thin', post: post %>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-md-4 section">
      <div class="options-section">
        <div class="options-heading">
          Recent Members
        </div>
        <div class="options-content">
          <ul class="list-group">
            <% @users.each do |user|%>
              <li class="list-group-item">
              <%= link_to user.displayname, user %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
      <div class="options-section">
        <div class="options-heading">
          Topics
        </div>
        <div class="options-content">      
          <div class="btn-group col-xs-12" data-toggle="buttons">
            <% @topics.each do |topic|%>
            <label class="btn btn-default">
              <input type="checkbox" name="<%=topic.name%>" value="<%=topic.name%>"><%=topic.name%>
            </label>
            <% end %>
          </div>
          </br>
          </br>
          </br>
          </br>
        </div>
      </div>
      <div class="options-section">
        <div class="options-heading">
          Posts
        </div>
        <div class="options-content">      
          <table class="table table-condensed">
            <tbody>
              <% @topposts.each do |post|%>
              <tr>
                <td><%= link_to post.title, post %></td>
                <td><%= post.views %> views</td>
              </tr>  
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
      <div class="options-section">
        <div class="options-heading">
          Links
        </div>
        <div class="options-content">      
          <ul class="list-group">
            <button type="button" class="list-group-item" onclick='window.location.href = "https://www.rmit.edu.au/"'>RMIT</button>
            <button type="button" class="list-group-item" onclick='window.location.href = "https://rubyonrails.org/"'>RubyOnRails</button>
            <button type="button" class="list-group-item" onclick='window.location.href = "https://github.com/mattasymmetric"'>Matthew Walters (GitHub)</button>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<% provide(:title,"Edit user") %>
<h1>Update your profile</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
  <%= form_for(@user) do |f| %>
    <%= render'shared/error_messages' %> 
    <%= f.label:displayname %>
    <%= f.text_field:displayname , class:'form-control' %>
    <%= f.label:email %>
    <%= f.email_field:email , class:'form-control' %>
    <%= f.label:phone %>
    <%= f.text_field:phone , class:'form-control' %>
    <%= f.label:password %>
    <%= f.password_field:password, class:'form-control' %>
    <%= f.label:password_confirmation, "Confirmation" %>
    <%= f.password_field:password_confirmation, class:'form-control' %>
    <%= f.submit"Save changes", class:"btn btn-primary" %>
  <% end %>
  </div>
</div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign Up') %>
<div class="row">
    <div class="col-md-4 col-md-offset-4 user-session-form">
        <h1> Sign Up </h1>
        <%=form_for(@user, url: signup_path)do|f|%>
        <%=render'shared/error_messages'%>
            <%=f.label:email%>
            <%=f.email_field:email,class:'form-control'%>
            <%=f.label:phone%>
            <%=f.text_field:phone,class:'form-control'%>
            <%=f.label:password%>
            <%=f.password_field:password,class:'form-control'%>
            <%=f.label:password_confirmation,"Confirmation"%>
            <%=f.password_field:password_confirmation,class:'form-control'%>
            <%=f.submit"Create my account",class:"btn btn-primary"%>
        <%end%>
        <p class="form-link"><%=link_to"Already a user?", login_path%></p>
    </div>
</div> 

app/views/users/show.html.erb
<%provide(:title,@user.displayname)%>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%=gravatar_for@user%>
        <%=@user.displayname%>
        <% if logged_in? %>
          <% if @current_user.admin? && !current_user?(@user) %>
          | <%= link_to "Delete User", @user, method: :delete, 
            data: {confirm: "Are you sure you want to delete this user?"}%>
          <%end%>
        <%end%>
      </h1>
    </section>
  </aside>
</div>